### ISSUE TITLE
ms1searchpy fails with divide by zero

### ISSUE THREAD

**Issue by DarylWM** [markmipt/ms1searchpy#2] opened 2021-11-02 03:44 UTC
Hello, and thank you for making this tool available.

I'm having trouble running it on a timsTOF file that I converted with msconvert and feature detected with Biosaur. The command I'm using:

`ms1searchpy P3856_YHE211_1_Slot1-1_1_5104-biosaur.tsv -d Human_Yeast_Ecoli.fasta -ad 1`

The output:

```
Reading spectra ...
Number of peptide isotopic clusters: 457696
Running the search ...
p=0.5241039806971397
divide by zero encountered in log10
results for default search: number of identified proteins = 1
Running mass recalibration...
Calibrated mass shift:  -0.4996648577720902
Calibrated mass sigma in ppm:  0.4494416961789045
p=0.1687498705548537
divide by zero encountered in true_divide
results for default search after mass calibration: number of identified proteins = 0
Running RT prediction...
Traceback (most recent call last):
  File "/home/daryl/anaconda3/envs/py36/bin/ms1searchpy", line 8, in <module>
    sys.exit(run())
  File "/home/daryl/anaconda3/envs/py36/lib/python3.8/site-packages/ms1searchpy/search.py", line 42, in run
    main.process_file(args)
  File "/home/daryl/anaconda3/envs/py36/lib/python3.8/site-packages/ms1searchpy/main.py", line 478, in process_file
    return process_peptides(args)
  File "/home/daryl/anaconda3/envs/py36/lib/python3.8/site-packages/ms1searchpy/main.py", line 1024, in process_peptides
    RC = achrom.get_RCs_vary_lcp(ns2, nr2)
  File "/home/daryl/anaconda3/envs/py36/lib/python3.8/site-packages/pyteomics-4.4.1-py3.8.egg/pyteomics/achrom.py", line 544, in get_RCs_vary_lcp
    RC_dict = get_RCs(peptide_dicts, RTs, lcp, term_aa, labels=labels)
  File "/home/daryl/anaconda3/envs/py36/lib/python3.8/site-packages/pyteomics-4.4.1-py3.8.egg/pyteomics/achrom.py", line 439, in get_RCs
    RCs, res, rank, s = np.linalg.lstsq(np.array(composition_array),
  File "<__array_function__ internals>", line 5, in lstsq
  File "/home/daryl/anaconda3/envs/py36/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 2271, in lstsq
    _assert_2d(a, b)
  File "/home/daryl/anaconda3/envs/py36/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 191, in _assert_2d
    raise LinAlgError('%d-dimensional array given. Array must be '
numpy.linalg.LinAlgError: 1-dimensional array given. Array must be two-dimensional
```

I'm using ms1searchpy 2.1.5 and diffacto 1.0.6. The installation steps (Ubuntu 18.04, Python 3.8.5 Conda envuronment):
```
pip install ms1searchpy
pip install https://github.com/statisticalbiotechnology/diffacto/archive/master.zip
```

I converted the timsTOF database using msconvert  with `msLevel=1` and `Combine ion mobility scans` enabled.

I executed biosaur 2.0.1 like this:
`biosaur P3856_YHE211_1_Slot1-1_1_5104.mzML --min_intensity 100 -out P3856_YHE211_1_Slot1-1_1_5104-biosaur.tsv`

Have I done something obviously wrong, or can I provide more information?

Best regards,
Daryl.

**Comment by markmipt** [comment] 2021-11-02 10:04
Dear Daryl,

It seems like you have done everything right. The specific problem here in your analysis is that “results for default search after mass calibration: number of identified proteins = 0”. That means that there are no proteins identified at the preliminary identification stage before retention time prediction model training and ms1searchpy ends work with an error (yeah, we should work on more clear error printing).

I believe that this issue is caused by TIMS-TOF itself and not by any problems with your data or data analysis workflow. In our experiments with TIMS-TOF data we have managed to identify only 200-300 proteins using the standard HeLa digest (for comparison, we usually have 1500-3500 proteins for Orbitraps). The tricks which can help with TIMS-TOF are:

Try “-cmin 2” option for ms1searchpy to remove single-charged features. TOF data contains more noise peaks compared to Orbitraps/ICR.
Try different values for “-sc X” option to remove peptide features which were detected in less than X MS1 scans. Again, that could help to deal with noise. I suggest trying 5, 10 and 20 values for the beginning.
You can also try different intensity thresholds in Biosaur.

But again, Orbitrap data usually works perfectly out of the box with no scans, intensity, charge and any other parameters tuning. TOF results with ms1searchpy are not so good (we tried both TIMS-TOF and standard Impact II data) right now, but this is one of our future research plans for DirectMS1 development.

Regards,
Mark

**Comment by DarylWM** [comment] 2021-11-03 04:54
Thank you for your reply Mark. With your suggestions I have made some progress. I used the Bruker denoising tool 1.4 to process the raw file and ran biosaur with `--min_intensity 1` to produce a TSV file, which I processed with ms1searchpy:

`ms1searchpy P3856_YHE211_1_Slot1-1_1_5104-denoised-biosaur-min-1.tsv -d ./tfde/fasta/Human_Yeast_Ecoli.fasta -ad 1 -sc 1 -cmin 2`

The minimum scans setting does seem short (this is a PASEF-mode acquisition with frame rate of 100ms, ms1 followed by 4 x ms2 frames, so the ms1 period is 500ms), but with these settings I was able to get past my original problem of no proteins in the initial pass.

Now it seems there's a missing features file:

```
Reading spectra ...
Number of peptide isotopic clusters: 248957
Running the search ...
p=0.49001059560787447
divide by zero encountered in log10
results for default search: number of identified proteins = 6
Running mass recalibration...
Calibrated mass shift:  0.003484261485827195
Calibrated mass sigma in ppm:  0.6069915917858058
p=0.2680403824781288
results for default search after mass calibration: number of identified proteins = 3
Running RT prediction...
`rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
Calibrated RT shift:  14.072262816983978
Calibrated RT sigma:  167.84942203012946
1.0000000000000053 -8.187319736287498e-12 0.5960314321564297 156.67710787613856
Running second stage RT prediction...
Calibrated RT shift:  15.984385316668439
Calibrated RT sigma:  181.0986311532948
1.0000000000000029 -4.004280403593371e-12 0.5678799114632789 150.68135462002877
Start Machine Learning on PFMs...
Features used for MachineLearning:  Index(['Is', 'Isotopes', 'mzraw', 'rt', 'ch', 'im', 'mass_diff', 'rt_diff',
       'plen', 'mass', 'pI', 'charge_theor', 'rt_diff_abs',
       'rt_diff_abs_pdiff', 'rt_diff_abs_pnorm', 'id_count', 'seq_count'],
      dtype='object')
1/25
Found `n_estimators` in params. Will use it instead of argument

A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
2/25
3/25
4/25
5/25
6/25
7/25
8/25
9/25
10/25
11/25
12/25
13/25
14/25
15/25
16/25
17/25
18/25
19/25
divide by zero encountered in true_divide
20/25
21/25
22/25
23/25
24/25
25/25
6497.0
p=0.4903240598017145
TOP 5 identified proteins:
dbname	score	num matched peptides	num theoretical peptides
results:P3856_YHE211_1_Slot1-1_1_5104-denoised-biosaur-min-1;number of identified proteins = 0
Traceback (most recent call last):
  File "/home/daryl/anaconda3/envs/py36/bin/ms1searchpy", line 8, in <module>
    sys.exit(run())
  File "/home/daryl/anaconda3/envs/py36/lib/python3.8/site-packages/ms1searchpy/search.py", line 42, in run
    main.process_file(args)
  File "/home/daryl/anaconda3/envs/py36/lib/python3.8/site-packages/ms1searchpy/main.py", line 478, in process_file
    return process_peptides(args)
  File "/home/daryl/anaconda3/envs/py36/lib/python3.8/site-packages/ms1searchpy/main.py", line 1550, in process_peptides
    final_iteration(resdict, mass_diff, rt_diff, pept_prot, protsN, base_out_name, prefix, isdecoy, isdecoy_key, escore, fdr, args['nproc'], fname)
  File "/home/daryl/anaconda3/envs/py36/lib/python3.8/site-packages/ms1searchpy/main.py", line 417, in final_iteration
    df0 = pd.read_table(os.path.splitext(fname)[0].replace('.features', '') + '.features' + '.tsv')
  File "/home/daryl/anaconda3/envs/py36/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/daryl/anaconda3/envs/py36/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 683, in read_table
    return _read(filepath_or_buffer, kwds)
  File "/home/daryl/anaconda3/envs/py36/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/daryl/anaconda3/envs/py36/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/daryl/anaconda3/envs/py36/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/daryl/anaconda3/envs/py36/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/daryl/anaconda3/envs/py36/lib/python3.8/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/daryl/anaconda3/envs/py36/lib/python3.8/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'P3856_YHE211_1_Slot1-1_1_5104-denoised-biosaur-min-1.features.tsv'
```

Regards,
Daryl.

**Comment by DarylWM** [comment] 2021-11-08 05:02
Closing this because the original problem was due to not finding proteins in the first pass.

**Comment by markmipt** [comment] 2021-11-08 10:59
Dear Daryl, 

Thanks for reporting issues with ms1searchpy. The latter "FileNotFoundError" error was due to ms1searchpy expected to have filenames with mask *.features.tsv (standard output of Dinosaur/Biosaur). I've fixed that in the last commit.

But you will get no resulting tables since "results:P3856_YHE211_1_Slot1-1_1_5104-denoised-biosaur-min-1;number of identified proteins = 0". That means that at final stage on analysis there is no proteins at 1% FDR.

I still suggest you to try higher "-sc" values. The logic behind that: we usually have 250-500 ms1 period in our 5min LC MS1-only experiments where width of peptide elution profile is ~2s. Your LC gradient is probably higher (my guess that it is  30min) and width of elution profile should be also higher.

Also, you should try to install and use DeepLC for RT prediction (see "Example for full installation and usage" at the README page). For example, my latest results for Orbitrap data: 1100 proteins at 1% FDR with simple RT prediction (your current case) transfers to 2200 proteins when DeepLC is applied.

If you want, I can try to analyse one of your files by myself. I have a new (and more efficient) versions of both ms1searchpy and biosaur which are under development and not committed to the github. I need mzML file for that (It would be a perfect case if you share both denoised and undenoised versions of the same file. I have never worked with that Bruker tool and have no idea if that improves or hurts results). But anyway, I don't expect really good results for ms1searchpy with TOF compared to Orbitrap data right now. You can contact me by email: markmipt@gmail.com

P.S. You are right, that is another issue but it is easier to continue here since you are already posted the traceback.

Best regards,
Mark

**Comment by DarylWM** [comment] 2021-11-09 05:25
Dear Mark,

> I still suggest you to try higher "-sc" values.

Yes I see. My gradient is 20 minutes. It's PASEF mode with 1 x MS scan and 4 x MS/MS scans, total cycle time of 1.27 seconds. I am experimenting with various values of `-sc`.

> Also, you should try to install and use DeepLC for RT prediction.

I have switched to using DeepLC.

> If you want, I can try to analyse one of your files by myself.

I will send you one of my sample analyses, in original and de-noised mzML versions. The upload speed of my internet connection isn't amazing when I'm working from home so it will take some time for a 11GB compressed file.

Best regards,
Daryl.

**Comment by DarylWM** [comment] 2021-11-09 09:03
Dear Mark,

The Biosaur analysis of the denoised data yields about 600K features, but DirectMS1 doesn't seem to find many proteins from them.

```
(py36) daryl@deep-thought-home:~$ biosaur P3856_YHE211_1_Slot1-1_1_5104-denoised.mzML --min_intensity 1 -out P3856_YHE211_1_Slot1-1_1_5104-denoised-biosaur-mi-1.tsv
JSON format is not enabled, normal log will be in plain text but request logging still in JSON format! To enable set ENABLE_JSON_LOGGING env var to either one of following values: ['true', '1', 'y', 'yes']
__init__.py[LINE:143]#WARNING  [2021-11-09 17:20:31,440] JSON format is not enabled, normal log will be in plain text but request logging still in JSON format! To enable set ENABLE_JSON_LOGGING env var to either one of following values: ['true', '1', 'y', 'yes']
2021-11-09 17:20:31 deep-thought-home root[8267] INFO Starting program with following params...
2021-11-09 17:20:31 deep-thought-home root[8267] INFO Starting with args: {
  "input_mzml_path": [
    "P3856_YHE211_1_Slot1-1_1_5104-denoised.mzML"
  ],
  "number_of_processes": 0,
  "correlation_map": false,
  "negative_mode": false,
  "mass_accuracy": 8,
  "min_charge": 1,
  "max_charge": 6,
  "min_length": 3,
  "min_length_hill": 2,
  "min_intensity": 1.0,
  "hill_valley_factor": 1.3,
  "debug": false,
  "output_file": "P3856_YHE211_1_Slot1-1_1_5104-denoised-biosaur-mi-1.tsv",
  "pep_xml_file_path": "0"
}
2021-11-09 17:20:31 deep-thought-home root[8267] INFO Reading scans...
2021-11-09 17:21:04 deep-thought-home root[8267] INFO Number of MS1 scans: 9441
2021-11-09 17:21:04 deep-thought-home root[8267] INFO Converting your data, using maximum amount of processes...
2021-11-09 17:58:15 deep-thought-home root[8338] INFO Data converted to features with process /1/ --->
2021-11-09 17:58:15 deep-thought-home root[8340] INFO Data converted to features with process /3/ --->
2021-11-09 17:58:15 deep-thought-home root[8339] INFO Data converted to features with process /2/ --->
2021-11-09 17:58:18 deep-thought-home root[8361] INFO Data converted to features with process /21/ --->
2021-11-09 17:58:18 deep-thought-home root[8362] INFO Data converted to features with process /22/ --->
2021-11-09 17:58:18 deep-thought-home root[8359] INFO Data converted to features with process /19/ --->
2021-11-09 17:58:18 deep-thought-home root[8363] INFO Data converted to features with process /23/ --->
2021-11-09 17:58:18 deep-thought-home root[8360] INFO Data converted to features with process /20/ --->
2021-11-09 17:58:18 deep-thought-home root[8365] INFO Data converted to features with process /25/ --->
2021-11-09 17:58:18 deep-thought-home root[8364] INFO Data converted to features with process /24/ --->
2021-11-09 17:58:19 deep-thought-home root[8366] INFO Data converted to features with process /26/ --->
2021-11-09 17:58:19 deep-thought-home root[8358] INFO Data converted to features with process /18/ --->
2021-11-09 17:58:19 deep-thought-home root[8367] INFO Data converted to features with process /27/ --->
2021-11-09 17:58:19 deep-thought-home root[8369] INFO Data converted to features with process /29/ --->
2021-11-09 17:58:19 deep-thought-home root[8368] INFO Data converted to features with process /28/ --->
2021-11-09 17:58:19 deep-thought-home root[8370] INFO Data converted to features with process /30/ --->
2021-11-09 17:58:20 deep-thought-home root[8371] INFO Data converted to features with process /31/ --->
2021-11-09 17:58:20 deep-thought-home root[8373] INFO Data converted to features with process /33/ --->
2021-11-09 17:58:20 deep-thought-home root[8372] INFO Data converted to features with process /32/ --->
2021-11-09 17:58:20 deep-thought-home root[8374] INFO Data converted to features with process /34/ --->
2021-11-09 17:58:20 deep-thought-home root[8380] INFO Data converted to features with process /36/ --->
2021-11-09 17:58:20 deep-thought-home root[8377] INFO Data converted to features with process /35/ --->
2021-11-09 17:58:21 deep-thought-home root[8341] INFO Data converted to features with process /4/ --->
2021-11-09 17:58:21 deep-thought-home root[8357] INFO Data converted to features with process /17/ --->
2021-11-09 17:58:31 deep-thought-home root[8356] INFO Data converted to features with process /16/ --->
2021-11-09 17:58:42 deep-thought-home root[8342] INFO Data converted to features with process /5/ --->
2021-11-09 17:58:46 deep-thought-home root[8355] INFO Data converted to features with process /15/ --->
2021-11-09 17:58:52 deep-thought-home root[8354] INFO Data converted to features with process /14/ --->
2021-11-09 17:59:07 deep-thought-home root[8353] INFO Data converted to features with process /13/ --->
2021-11-09 17:59:17 deep-thought-home root[8343] INFO Data converted to features with process /6/ --->
2021-11-09 17:59:19 deep-thought-home root[8348] INFO Data converted to features with process /11/ --->
2021-11-09 17:59:20 deep-thought-home root[8349] INFO Data converted to features with process /12/ --->
2021-11-09 17:59:36 deep-thought-home root[8347] INFO Data converted to features with process /10/ --->
2021-11-09 17:59:49 deep-thought-home root[8346] INFO Data converted to features with process /9/ --->
2021-11-09 17:59:58 deep-thought-home root[8344] INFO Data converted to features with process /7/ --->
2021-11-09 18:00:06 deep-thought-home root[8345] INFO Data converted to features with process /8/ --->
2021-11-09 18:01:47 deep-thought-home root[8267] INFO All data converted to hills...
2021-11-09 18:01:47 deep-thought-home root[8267] INFO Processing hills...
2021-11-09 18:01:47 deep-thought-home root[8267] INFO Your hills proccesing with maximum amount of processes...
2021-11-09 18:01:47 deep-thought-home root[8267] INFO 3795880 hills were detected...
2021-11-09 18:01:47 deep-thought-home root[8267] INFO 3795880 hills were detected...
2021-11-09 18:01:52 deep-thought-home root[8267] INFO Start recalc_fast_array_for_finished_hills...
2021-11-09 18:01:57 deep-thought-home root[8267] INFO Start boosting_secondstep_with_processes...
2021-11-09 18:09:30 deep-thought-home root[8422] INFO All hills were iterated correctly with this process /12/ -->
2021-11-09 18:15:02 deep-thought-home root[8411] INFO All hills were iterated correctly with this process /1/ -->
2021-11-09 18:15:33 deep-thought-home root[8421] INFO All hills were iterated correctly with this process /11/ -->
2021-11-09 18:15:46 deep-thought-home root[8420] INFO All hills were iterated correctly with this process /10/ -->
2021-11-09 18:18:34 deep-thought-home root[8419] INFO All hills were iterated correctly with this process /9/ -->
2021-11-09 18:19:55 deep-thought-home root[8418] INFO All hills were iterated correctly with this process /8/ -->
2021-11-09 18:29:31 deep-thought-home root[8417] INFO All hills were iterated correctly with this process /7/ -->
2021-11-09 18:29:37 deep-thought-home root[8415] INFO All hills were iterated correctly with this process /5/ -->
2021-11-09 18:29:38 deep-thought-home root[8412] INFO All hills were iterated correctly with this process /2/ -->
2021-11-09 18:30:18 deep-thought-home root[8416] INFO All hills were iterated correctly with this process /6/ -->
2021-11-09 18:30:52 deep-thought-home root[8413] INFO All hills were iterated correctly with this process /3/ -->
2021-11-09 18:30:56 deep-thought-home root[8414] INFO All hills were iterated correctly with this process /4/ -->
=========================================================== 

2021-11-09 18:47:46 deep-thought-home root[8267] INFO Ready!
2021-11-09 18:47:46 deep-thought-home root[8267] INFO 599649 features were detected.
2021-11-09 18:47:46 deep-thought-home root[8267] INFO All your features were saved in P3856_YHE211_1_Slot1-1_1_5104-denoised-biosaur-mi-1.tsv
2021-11-09 18:47:46 deep-thought-home root[8267] INFO Total time: 87.3 minutes.
```


```
ms1searchpy P3856_YHE211_1_Slot1-1_1_5104-denoised-biosaur-mi-1.tsv -d ./tfde/fasta/Human_Yeast_Ecoli.fasta -ad 1 -sc 30 -cmin 2 -deeplc ./anaconda3/envs/py36/bin/deeplc
./tfde/fasta/Human_Yeast_Ecoli_shuffled.fasta
Reading spectra ...
Number of peptide isotopic clusters: 70
Running the search ...
p=0.003085916575447749
results for default search: number of identified proteins = 1
Running mass recalibration...
Calibrated mass shift:  2.438500000021803
Calibrated mass sigma in ppm:  0.024718633776855344
p=1.940828034872798e-05
results for default search after mass calibration: number of identified proteins = 2
Running RT prediction...
`rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
Covariance of the parameters could not be estimated
Traceback (most recent call last):
  File "/home/daryl/anaconda3/envs/py36/bin/ms1searchpy", line 8, in <module>
    sys.exit(run())
  File "/home/daryl/anaconda3/envs/py36/lib/python3.8/site-packages/ms1searchpy/search.py", line 42, in run
    main.process_file(args)
  File "/home/daryl/anaconda3/envs/py36/lib/python3.8/site-packages/ms1searchpy/main.py", line 448, in process_file
    return process_peptides(args)
  File "/home/daryl/anaconda3/envs/py36/lib/python3.8/site-packages/ms1searchpy/main.py", line 986, in process_peptides
    XRT_shift, XRT_sigma, covvalue = calibrate_RT_gaus(0.1, RT_left, RT_right, rt_diff_tmp)
  File "/home/daryl/anaconda3/envs/py36/lib/python3.8/site-packages/ms1searchpy/main.py", line 440, in calibrate_RT_gaus
    popt, pcov = curve_fit(noisygaus, b1, H1, p0=[1, np.median(true_md), bwidth * 5, 1])
  File "/home/daryl/anaconda3/envs/py36/lib/python3.8/site-packages/scipy-1.6.1-py3.8-linux-x86_64.egg/scipy/optimize/minpack.py", line 747, in curve_fit
    raise ValueError("`ydata` must not be empty!")
ValueError: `ydata` must not be empty!
```

It seems there's a very low number of isotopic clusters (70) for the number of features.

**Comment by markmipt** [comment] 2021-11-09 12:35
The number of isotopic clusters in the ms1searchpy logs is just the number of biosaur features after ms1searchpy filters (-cmin 2 and -sc 30). So, that just means that only 70 features (out of 599649) have >= 30 MS1 scans and charge >= 2.

**Comment by DarylWM** [comment] 2021-11-09 21:39
Thanks Mark. For my own feature detection algorithm I generally use an average peak width of 10-20 seconds for this gradient. This is the effect of varying `-sc` in ms1searchpy...

`-sc` | isotopic clusters | proteins in default search | proteins after mass calib | peptides for RT pred
-----|-----|----|----|----
10 | 37032 | 0
20 | 1074 | 0
30 | 70 | 7 | 1 | 0
40 | 10 | 0

You've explained that isotopic clusters is how many features Biosaur detected, filtered by minimum scans and charge, but I don't understand why the number of proteins in the default search seems to decrease as the number of features increases.

**Comment by markmipt** [comment] 2021-11-25 09:14
Explained in email correspondence

**Closed as completed by markmipt** 2021-11-25 09:14 UTC
